/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_liang_gpio_demo_Gpio */

#ifndef _Included_com_example_liang_gpio_demo_Gpio
#define _Included_com_example_liang_gpio_demo_Gpio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_liang_gpio_demo_Gpio
 * Method:    Set_GPIO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_liang_gpio_1demo_Gpio_Set_1GPIO
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
